### PR TITLE
Icon large rights statement under download button

### LINKED ISSUE #332: Implement rights / usage disclaimer
Design needed.

### PR DESCRIPTION
**Pull request by jrochkind**
It currently just uses Hevetica for now. Our whole site just uses
Helvetica. It ain't super pretty, but I think it makes more sense
to wait till we make this whole page pretty after soft launch, then
micro-design this particular element on a page that is otherwise
still pretty messy and without really style determined.

Closes #332

### CODE REVIEW

**Comment by hackmastera** [comment]
@jrochkind can you add some screenshots?

Also, question: does this resolve 332 completely, including public domain stuff? Or is PD still outstanding?

**Comment by jrochkind** [comment]
PD is in there. 
screen shot 2017-04-12 at 4 05 52 pm
screen shot 2017-04-12 at 4 06 28 pm

**Comment by hackmastera** [comment]
Looks great. I'm +1 to merge once @MDiMeo approves; I expect she'll want to look at these screenshots and also the short_labels in the config file https://github.com/chemheritage/chf-sufia/pull/464/files#diff-55503801f6191f823339313ab394b8ff

**Comment by MDiMeo** [comment]
Yes, this works for me. Resolves #332 too. Thanks!!

**Comment by jrochkind** [comment]
Cool. The labels next to the buttons are all taken from the rightsstatements.org buttons, and match. except for "Public Domain", of course, which is not taken from there, and is just "Public Domain".

**Pull request merged**
