### PR TITLE
Stop relying on local ssh config

### PR DESCRIPTION
**Pull request by hackmastera**

### CODE REVIEW

**Comment by jrochkind** [comment]
I was about to merge this, but noted it was titled "[WIP - untested]", so I didn't!

**Comment by jrochkind** [comment]
Tried to deploy with this one, nope. 

~~~bash
$ bundle exec cap staging deploy
00:00 git:wrapper
      01 mkdir -p /tmp
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host staging.digital.chemheritage.org: Authentication failed for user jrochkind@staging.digital.chemheritage.org

Net::SSH::AuthenticationFailed: Authentication failed for user jrochkind@staging.digital.chemheritage.org

Tasks: TOP => deploy:check => git:check => git:wrapper
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing on host staging.digital.chemheritage.org: Authentication failed for user jrochkind@staging.digital.chemheritage.org


** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:


  INFO ---------------------------------------------------------------------------

  INFO START 2017-06-19 17:33:53 -0400 cap staging deploy

  INFO ---------------------------------------------------------------------------

  INFO [b2918d0a] Running /usr/bin/env mkdir -p /tmp on solr_staging

  INFO [e884a2fe] Running /usr/bin/env mkdir -p /tmp on staging

  INFO [b2918d0a] Finished in 0.842 seconds with exit status 0 (successful).

  INFO [e884a2fe] Finished in 1.110 seconds with exit status 0 (successful).

  INFO Uploading /tmp/git-ssh-chf-sufia-staging-jrochkind.sh 100.0%

  INFO [c158f773] Running /usr/bin/env chmod 700 /tmp/git-ssh-chf-sufia-staging-jrochkind.sh on staging

  INFO [c158f773] Finished in 0.041 seconds with exit status 0 (successful).

  INFO ---------------------------------------------------------------------------

  INFO START 2017-06-19 17:36:50 -0400 cap staging deploy

  INFO ---------------------------------------------------------------------------

  INFO [c878cbb5] Running /usr/bin/env mkdir -p /tmp on staging.digital.chemheritage.org

  INFO [8804cd14] Running /usr/bin/env mkdir -p /tmp on 184.73.72.239

  INFO ---------------------------------------------------------------------------

  INFO START 2017-06-19 17:37:16 -0400 cap staging deploy

  INFO ---------------------------------------------------------------------------

  INFO [9c9c9761] Running /usr/bin/env mkdir -p /tmp on staging.digital.chemheritage.org

  INFO [4a2f0d4f] Running /usr/bin/env mkdir -p /tmp on 184.73.72.239


jrochkind@macbook chf-sufia (ssh-config ?) $
~~~

**Comment by jrochkind** [comment]
Okay, I don't think the `user` variable is being used for whatever reason. 

If I change these lines like so:

~~~
server 'staging.digital.chemheritage.org', roles: [:web, :app, :db, :jobs], user: 'hydep'
server '184.73.72.239', roles: [:solr], user: 'hydep'
~~~

Then I'm back to the same error I get when trying to deploy off master with .ssh/config:

    The deploy has failed with an error: Exception while executing as hydep@184.73.72.239: scp: /tmp/git-ssh-chf-sufia-staging-jrochkind.sh: Permission denied

Got me. 

I don't think I have root on that machine, but @sanfordd , you want to log into 184.73.72.239 and see if there's a `/tmp/git-ssh-chf-sufia-staging-jrochkind.sh`, and delete it if there is?

**Comment by hackmastera** [comment]
Thank you for testing, and for fixing the user variable. I'm not sure how it knows you are jrochkind when you execute as hydep. in fact, I think when I deploy it knows i'm logging in as the system user. but i thought cap used the deploy user for everything.

**Comment by jrochkind** [comment]
I should try again with a completely blank .ssh/config.  It may be something in there wrong. 

The user thing I didn't fix in this branch though, I was confused about how cap was "supposed" to work.

**Comment by hackmastera** [comment]
Okay I added that user fix in, squashed it with the first commit, then force pushed back to this branch.

This is now working for me, regardless the contents of my `.ssh/config`. Maybe @jrochkind is having a key issue? @sanfordd

**Comment by jrochkind** [comment]
@hackmastera is this actually working reliably for you, or are you still having that "permissions on /tmp file" issue?  Confused between here and slack.

**Comment by hackmastera** [comment]
@jrochkind moving the user config into the server line fixed it for me.

**Comment by jrochkind** [comment]
worked for me!

**Pull request merged**
