### PR TITLE
Add desired fields to 'all fields' search, fixes #351

### LINKED ISSUE #351: List of fields that should be searched with keyword 'all fields' search

### PR DESCRIPTION
**Pull request by hackmastera**
This PR includes 2 other cleanup-type commits for my own convenience but let me know if you prefer them split out.

### CODE REVIEW

**Comment by jrochkind** [comment]
@hackmastera It's interesting that the Hydra/Sufia way to do this seems to be index every property in their own Solr field, and then list all the solr fields in the solr configuration to search.  In the past, I would have done this different -- if there were different properties which should all be searchable with the same level of 'relevant boosting', I'd aggregate them in the _same_ Solr field; that's more how Solr is intended to be used I think, but this alternate Hydra way should work too, sure. 

but I'm gonna ask on Hydra Slack what the context for this is, cause I'm curious. 

Also gonna spend some more time with this PR as an entry point to understanding what's going on. 

(Note, I'm not asking for changes, I'll merge it, just discusisng).

**Comment by hackmastera** [comment]
@jrochkind good point. thanks!

**Comment by jrochkind** [comment]
I think this approach is going to be a lot less performant for Solr, to have to include dozens of fields in the search instead of a handful. But that may not matter at the scale we are at.

**Comment by hackmastera** [comment]
We'll have to index them all anyway, but it would be easy to create an 'keyword search' solr copy field instead and then define that as the target for 'all fields'.

**Comment by jrochkind** [comment]
Why do we have to index them all seperately anyway?

Here's the slack discussion. https://project-hydra.slack.com/archives/dev/p1489420198226279

**Comment by hackmastera** [comment]
The reason we index them separately is so they can be displayed on a record page without hitting fedora.

**Comment by hackmastera** [comment]
right; re: the slack discussion, we looked at the local indexer a bit when we were in the gerstacker room. it's here https://github.com/chemheritage/chf-sufia/blob/master/app/indexers/generic_work_indexer.rb

**Pull request merged**
