### PR TITLE
Smaller front-page hero

### PR DESCRIPTION
**Pull request by jrochkind**
With changes and crazy arithmatic to try to keep whitespace and alignment looking good at all
screen sizes.

Ref #761

### CODE REVIEW

**Comment by jrochkind** [comment]
@MDiMeo I tried to make the image smaller while changing as little else as possible. Still had to change a bunch of other things and do some weird arithmatic to try to keep the white space and alignment looking good at any screen size, and keep the content from getting too large and making white space under the hero image at some screen sizes. 

I can demo it on staging when you are back. 

Here is a screenshot at a very large screen size:

very big screen

Here is a screenshot at the smallest screen size before it wraps to one column:

just before wrap

Is this basically what you were imagining?

**Comment by jrochkind** [comment]
@MDiMeo a 50% screen width version is currently live on Staging.

**Comment by jrochkind** [comment]
Per discussion, if you want a different aspect ratio, you or someone else can certainly do a crop with the aspect ratio you want and we can try that.

**Comment by MDiMeo** [comment]
@jrochkind Thanks! I mostly like it at 50%. My only issue is that it has significant white space under the hero image that I think has the unintended result of making the page look less professional. Can you see that on your screen or do you want a screen shot of what I see when I load it? And would that be a huge pain to eliminate that white space?

**Comment by jrochkind** [comment]
Screen shot _under_ the hero image?  Yes, I don't see that, screen shot please.

**Comment by MDiMeo** [comment]
staging screenshot
There was white space on both of @catlu's monitors, too. We both agreed that if the white space was removed that the 50% screen width would be a slight improvement on what we currently have.

**Comment by jrochkind** [comment]
OK, thanks, I'm having trouble reproducing that. Can you tell me what browser you are using, and if that white line appears at all sizes as you resize your browser window, or only at certain ones?

**Comment by MDiMeo** [comment]
I have been using Chrome and yes, it stays the same size as I resize my window. But I just tried it in IE and don't see it there.

**Comment by jrochkind** [comment]
Odd, I don't see it in MacOS Chrome, Safari, or Firefox; or Windows IE11. 

I forget, are you on Windows Chrome?

**Comment by MDiMeo** [comment]
Yes. And so is Cat. We can ask @sanfordd to check his when he's back from lunch. I'm signing off for a short bit now, too.

**Comment by jrochkind** [comment]
I successfully reproduced the problem on Windows Chrome, okay!  Wow, it's been a while since i saw a difference between a browser on Windows and Mac, that doesn't really happen anymore! But is here! 

Okay, when I get that fixed, shall I merge to master and deploy to production?

**Comment by jrochkind** [comment]
OK, with white space fixed, merging and deploying to prod.

**Pull request merged**
